<div style="text-align: center;">
    <img src="https://rubikcloud.ai/wp-content/uploads/2024/03/logo-bottom.png" alt="Image" width="200"/>
</div>


<p align="center">
  <strong style="font-size: 44px;">Trabajo Practico 2: Reconstruccion 3D</strong><br>
  <em style="font-size: 16px;">Codigo de Bruno Castagnino Rossi, Olivia Browne Corbacho y Agustin Federico Manzano - Parte 1</em>
</p>

In [1]:
import pickle as pkl
import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt
import os 
import sys
import open3d as o3d
import calib

In [2]:
from code import initiation

path1 = 'data/captures/left_3.jpg'
path2 = 'data/captures/left_3.jpg'

pklpath = 'data/stereo_maps.pkl'

imgL, imgR, mat_dict = initiation(path1, path2, pklpath)

In [3]:
from code import open_pkl

mat_dict, stereo_calib = open_pkl('data/stereo_maps.pkl', 'data/stereo_calibration.pkl')

print(mat_dict['Q'])
print(mat_dict.keys())

print(stereo_calib.keys())
print(stereo_calib['left_K'])
print(stereo_calib['left_dist'])


[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00 -9.70262848e+02]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00 -5.39484238e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  6.00600906e+02]
 [ 0.00000000e+00  0.00000000e+00  1.66848275e-02 -0.00000000e+00]]
dict_keys(['left_map_x', 'left_map_y', 'right_map_x', 'right_map_y', 'R1', 'R2', 'P1', 'P2', 'Q', 'validRoi1', 'validRoi2'])
dict_keys(['left_K', 'left_dist', 'right_K', 'right_dist', 'R', 'T', 'E', 'F', 'image_size'])
[[601.92838937   0.         959.61909931]
 [  0.         602.57590677 547.75865163]
 [  0.           0.           1.        ]]
[[ 1.81316452e-03 -2.16045131e-02 -6.59116213e-04  9.60877050e-05
   3.24259481e-03]]


In [4]:
from code import show_rectified_images
show_rectified_images(imgL, imgR, mat_dict, plot_images=True)

In [5]:
from code import save_imgs

save_imgs(mat_dict)
    

Rectified images saved to data/rectified_images
Rectified images 0 saved
Rectified images saved to data/rectified_images
Rectified images 1 saved
Rectified images saved to data/rectified_images
Rectified images 2 saved
Rectified images saved to data/rectified_images
Rectified images 3 saved
Rectified images saved to data/rectified_images
Rectified images 4 saved
Rectified images saved to data/rectified_images
Rectified images 5 saved
All images saved


In [6]:
#importamos el código de gaston para construir mapas de disparidad de cada par de imágenes rectificadas
from disparity_example import *

In [7]:
from code import compute_disparity

calibration_path = "/Users/brunocr/Desktop/UDESA/Visión Artificial/TP2_Reconstruccion3D/VA_TP2/calibration_tool/data/rectified_images/stereodemo_calibration.json"
compute_disparity(calibration_path)



Computing disparity...


/Users/brunocr/opt/anaconda3/envs/stereodemoenv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CoreMLExecutionProvider, AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(


Computing disparity...
Computing disparity...
Computing disparity...
Computing disparity...
Computing disparity...


In [8]:
from code import *

In [9]:
pcd_camara_tuples = pcd(mat_dict, stereo_calib)

In [10]:
visualize(pcd_camara_tuples)

In [11]:
# for i, (pcd_filtered, _) in enumerate(pcd_camara_tuples):
#     save_pcd_to_ply(pcd_filtered, f"filtered_output_{i}.ply")
